"""
Generate professional PDF reports for dashboard submissions and their click metadata.
"""
import io
import re
from django.conf import settings
from django.utils import timezone as django_tz

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)

# Professional color palette
COLOR_HEADER = colors.HexColor('#1e3a5f')
COLOR_ACCENT = colors.HexColor('#2563eb')
COLOR_SECTION_BG = colors.HexColor('#f8fafc')
COLOR_BORDER = colors.HexColor('#e2e8f0')
COLOR_TEXT = colors.HexColor('#1e293b')
COLOR_TEXT_MUTED = colors.HexColor('#64748b')
COLOR_FOOTER = colors.HexColor('#94a3b8')

FOOTER_TEXT = "This document was automatically generated by Software"
PDF_WATERMARK_TEXT = getattr(settings, "PDF_WATERMARK_TEXT", "Sales Capture")


def _sanitize(s, max_len=200):
    """Make string safe for PDF and truncate if needed."""
    if s is None:
        return "—"
    s = str(s).strip()
    s = re.sub(r'[\x00-\x08\x0b\x0c\x0e-\x1f]', '', s)
    return (s[:max_len] + '…') if len(s) > max_len else s or "—"


def _format_geo(click):
    g = getattr(click, 'geo_location', None) or {}
    parts = [g.get('city'), g.get('region'), g.get('country')]
    parts = [p for p in parts if p]
    result = ", ".join(parts) if parts else "—"
    if g.get('isp'):
        result += f" · {_sanitize(g.get('isp'), 80)}"
    return result or "—"


def _format_browser(click):
    b = getattr(click, 'browser', None) or {}
    name = b.get('name') or "—"
    ver = b.get('version', '')
    if ver:
        name += f" {ver}"
    return _sanitize(name, 100)


def _format_device(click):
    d = getattr(click, 'device', None) or {}
    parts = [d.get('type'), d.get('os'), d.get('platform'), d.get('memory')]
    parts = [p for p in parts if p]
    return _sanitize(", ".join(parts), 120) if parts else "—"


def _format_screen(click):
    s = getattr(click, 'screen', None) or {}
    res = s.get('resolution')
    vp = s.get('viewport')
    if res or vp:
        return _sanitize(f"{res or '—'} · {vp or '—'}", 80)
    return "—"


def _make_footer_canvas(doc, watermark_text=PDF_WATERMARK_TEXT):
    """Return a footer callback for SimpleDocTemplate. Draws watermark and footer."""

    def footer(canvas, _doc):
        width = _doc.pagesize[0]
        height = _doc.pagesize[1]

        # Watermark: low visibility, centered, diagonal
        if watermark_text:
            canvas.saveState()
            canvas.setFont('Helvetica-Bold', 48)
            canvas.setFillColor(colors.Color(0.7, 0.7, 0.7, alpha=0.12))
            canvas.translate(width / 2, height / 2)
            canvas.rotate(-45)
            canvas.drawCentredString(0, 0, watermark_text)
            canvas.restoreState()

        # Footer text
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(COLOR_FOOTER)
        canvas.drawCentredString(width / 2, 14 * mm, FOOTER_TEXT)
        canvas.drawCentredString(width / 2, 10 * mm, f"Page {canvas.getPageNumber()}")
        canvas.restoreState()

    return footer


def build_submissions_pdf(submissions):
    """
    Build a professional PDF containing submissions and their click metadata.
    Returns: bytes of the PDF.
    """
    buffer = io.BytesIO()
    pagesize = A4
    page_width = pagesize[0]
    content_width = page_width - 40 * mm

    doc = SimpleDocTemplate(
        buffer,
        pagesize=pagesize,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=24 * mm,
        bottomMargin=26 * mm,
    )

    styles = getSampleStyleSheet()
    story = []

    # --- Cover-style header ---
    generated = django_tz.now().strftime("%B %d, %Y at %H:%M UTC")
    title_style = ParagraphStyle(
        name='PdfTitle',
        parent=styles['Heading1'],
        fontSize=22,
        textColor=colors.white,
        fontName='Helvetica-Bold',
        spaceAfter=4,
        alignment=1,
    )
    subtitle_style = ParagraphStyle(
        name='PdfSubtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor('#cbd5e1'),
        spaceAfter=0,
        alignment=1,
    )
    header_content = [
        [Paragraph("Submission Report", title_style)],
        [Paragraph(generated, subtitle_style)],
    ]
    header_table = Table(header_content, colWidths=[content_width])
    header_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), COLOR_HEADER),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('LEFTPADDING', (0, 0), (-1, -1), 24),
        ('RIGHTPADDING', (0, 0), (-1, -1), 24),
        ('TOPPADDING', (0, 0), (-1, -1), 16),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 16),
    ]))
    story.append(header_table)
    story.append(Spacer(1, 10 * mm))

    story.append(Spacer(1, 6 * mm))

    for idx, sub in enumerate(submissions):
        # --- Section title with left accent bar ---
        name_style = ParagraphStyle(
            name=f'SectionName_{idx}',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=COLOR_HEADER,
            fontName='Helvetica-Bold',
            spaceBefore=0,
            spaceAfter=0,
            leftIndent=0,
        )
        section_title = Paragraph(f"{_sanitize(sub.name, 100)}", name_style)
        section_wrapper = Table([[section_title]], colWidths=[content_width])
        section_wrapper.setStyle(TableStyle([
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LINEBELOW', (0, 0), (-1, 0), 2, COLOR_ACCENT),
        ]))
        story.append(section_wrapper)
        story.append(Spacer(1, 4 * mm))

        # --- Contact & address data (clean key-value, no header row) ---
        sub_data = [
            ["Name", _sanitize(sub.name)],
            ["Phone", _sanitize(sub.phone)],
            ["Email", _sanitize(sub.email)],
            ["Address", _sanitize(sub.address)],
            ["City", _sanitize(sub.city)],
            ["Zip", _sanitize(sub.zip_code)],
            ["Country", _sanitize(sub.country)],
            ["Submitted", sub.created_at.strftime("%b %d, %Y at %H:%M") if sub.created_at else "—"],
        ]
        t = Table(sub_data, colWidths=[32 * mm, 133 * mm])
        t.setStyle(TableStyle([
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('TEXTCOLOR', (0, 0), (0, -1), COLOR_TEXT_MUTED),
            ('TEXTCOLOR', (1, 0), (1, -1), COLOR_TEXT),
            ('LEFTPADDING', (0, 0), (-1, -1), 8),
            ('RIGHTPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('LINEBELOW', (0, 0), (-1, 0), 0.5, COLOR_BORDER),
            ('LINEBELOW', (0, 1), (-1, -1), 0.25, colors.HexColor('#f1f5f9')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        story.append(t)
        story.append(Spacer(1, 6 * mm))

        rel = getattr(sub, 'click_metadata', None)
        clicks = list(rel.all()) if rel else []
        if clicks:
            # --- Click activity section ---
            clicks_title_style = ParagraphStyle(
                name='ClicksTitle',
                parent=styles['Heading3'],
                fontSize=11,
                textColor=COLOR_HEADER,
                fontName='Helvetica-Bold',
                spaceBefore=2,
                spaceAfter=4,
            )

            for click in clicks:
                ts = click.timestamp.strftime("%b %d, %Y %H:%M") if getattr(click, 'timestamp', None) else "—"
                click_data = [
                    ["IP Address", _sanitize(str(click.ip_address) if click.ip_address else "—")],
                    ["Location", _format_geo(click)],
                    ["Browser", _format_browser(click)],
                    ["Device", _format_device(click)],
                    ["Screen", _format_screen(click)],
                ]
                ct = Table(click_data, colWidths=[32 * mm, 133 * mm])
                ct.setStyle(TableStyle([
                    ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                    ('FONTSIZE', (0, 0), (-1, -1), 9),
                    ('TEXTCOLOR', (0, 0), (0, -1), COLOR_TEXT_MUTED),
                    ('TEXTCOLOR', (1, 0), (1, -1), COLOR_TEXT),
                    ('LEFTPADDING', (0, 0), (-1, -1), 8),
                    ('RIGHTPADDING', (0, 0), (-1, -1), 8),
                    ('TOPPADDING', (0, 0), (-1, -1), 5),
                    ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
                    ('BACKGROUND', (0, 0), (-1, -1), COLOR_SECTION_BG),
                    ('BOX', (0, 0), (-1, -1), 0.5, COLOR_BORDER),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ]))
                # Timestamp as small label above each click block
                ts_para = Paragraph(f"<font size='8' color='#64748b'>{ts}</font>", styles['Normal'])
                story.append(ts_para)
                story.append(Spacer(1, 1 * mm))
                story.append(ct)
                story.append(Spacer(1, 4 * mm))
        else:
            story.append(Spacer(1, 2 * mm))

        if sub is not submissions[-1]:
            story.append(Spacer(1, 4 * mm))
            story.append(PageBreak())

    footer_fn = _make_footer_canvas(doc)
    doc.build(story, onFirstPage=footer_fn, onLaterPages=footer_fn)
    buffer.seek(0)
    return buffer.getvalue()
